---
- name: Notify - Handlers
  hosts: all
  become: true
  gather_facts: no

  vars:
    - src_path: /opt/Playbooks
    - dest_path: /var/www/html

  tasks:
    - name: HTTPD Installation
      yum: 
       name: httpd
       state: installed

    - name: Services
      systemd:
        name: httpd
        state: started

    - name: Deploy Application
      copy:
         src: "{{ src_path }}/index.html"
         dest: "{{ dest_path }}"
      notify: Restart httpd services
  handlers:
    - name: Restart httpd services
      systemd:
         name: httpd
         state: restarted



