---
- name: HTTPD Service status
  hosts: all
  become: true
  tasks:
  - name: httpd Installation
    yum:
      name: httpd
      state: present
  - name: Start the service
    service: 
     name: httpd
     state: started
