---
- name: Maven Installtion
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Download Maven
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
      dest: /apache-maven-3.8.4-bin.tar.gz
      mode: '0755'
