---
- name: conditions
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: install httpd installation
      yum: 
        name: httpd
        state:  latest

      when: ansible_host  == 'Node2' 


